### ISSUE TITLE
Example site for Products

### ISSUE THREAD

**Issue by fatyogi** [Hugolify/hugolify-theme-products#1]
Bonjour Sébastien,

I have been trying to put together a simple shop front using `hugolify-theme-products` and I'm struggling with the documentation, which is very minimalistic. I created a sample product page using Sveltia CMS - out of the box it makes a directory `products/2025` with a single `my-sample-product.md` file in it, and the uploaded images in the same directory. 

However, after that - the layout template does not pick it up and does not show anything. Do you by any chance have an example site on GitHub where I can see how the content is provided to the products/* templates?

Even the source of [this example site](https://demo-products--hugolify-demo.netlify.app/) would be much appreciated.

Thanks,
Olaf

**Comment by sebousan** [comment]
Hi @fatyogi,

You can see Hugolify products demo’s source here: 
https://github.com/Hugolify/hugolify-template/tree/demo-products

I plan to make articles in the specific doc step by step, it's coming soon

I would be happy to help you if you share your repository with me.

Merci,
Seb

**Comment by fatyogi** [comment]
Looks like I managed to fix that, by adding all required fields manually (not using CMS) - thank you for your offer however! So far so good, however I have other issues which I may ask you about, if you don't mind?

For example, is there any way to control how these .webp images are being created/processed from the originals?  In this instance, I would like the pictures on the products here displayed at full sized rather than reduced to half size: 

<img width="775" alt="Image" src="https://github.com/user-attachments/assets/21d586ba-0c49-4999-853f-6477b23db446" />

And here, when the products are shown, a perfectly square 700x700 image of a bowl, with a bowl right in the middle of it, is shown as being cut off at one side or another - depending on the size of the media. Is there a way to control that the images are always centered and cut off accordingly around the center?

<img width="422" alt="Image" src="https://github.com/user-attachments/assets/65e23bb7-4a80-4cff-a904-edfca4712b1d" />

**Comment by sebousan** [comment]
Hi @fatyogi,

### Navigation image

you could set Params (`config/_default/params.yaml`) for the navigation images between, like this:
```yaml
Params:
  thumbnail:
    desktop: '414x' # or another, default is 414x177
    mobile: '300x' # or another, default is 300x129
```

But, I refine the possibility so that it is specific to the content type.

```yaml
Params:
  # default navigation 
  navigation:
    desktop: '200x'
    mobile: '200x'
  # or specific type navigation
  products:
    navigation:
      desktop: '200x' 
      mobile: '200x'
```

You need to update mods like this: `yarn update`

### Crop

you can set [image processing](https://gohugo.io/content-management/image-processing/#processing-options). in Hugo config (`config/_default/hugo.yaml`), 

```yaml
imaging:
  anchor: Center # default is Smart
```

I hope I was able to help you
Seb
